
local helpScreenImages = 
{
    rifle               = PrecacheAsset("ui/helpScreen/icons/rifle.dds"),
    rifleButt           = PrecacheAsset("ui/helpScreen/icons/rifle_butt.dds"),
    pistol              = PrecacheAsset("ui/helpScreen/icons/pistol.dds"),
    axe                 = PrecacheAsset("ui/helpScreen/icons/axe.dds"),
    welder              = PrecacheAsset("ui/helpScreen/icons/welder.dds"),
    shotgun             = PrecacheAsset("ui/helpScreen/icons/shotgun.dds"),
    mines               = PrecacheAsset("ui/helpScreen/icons/mine.dds"),
    flamethrower        = PrecacheAsset("ui/helpScreen/icons/flamethrower.dds"),
    grenadeLauncher     = PrecacheAsset("ui/helpScreen/icons/grenade_launcher.dds"),
    machineGun          = PrecacheAsset("ui/helpScreen/icons/machine_gun.dds"),
    clusterGrenade      = PrecacheAsset("ui/helpScreen/icons/grenade_cluster.dds"),
    pulseGrenade        = PrecacheAsset("ui/helpScreen/icons/grenade_pulse.dds"),
    gasGrenade          = PrecacheAsset("ui/helpScreen/icons/grenade_gas.dds"),
    minigun             = PrecacheAsset("ui/helpScreen/icons/mini_gun.dds"),
    railgun             = PrecacheAsset("ui/helpScreen/icons/rail_gun.dds"),
    exoThrusters        = PrecacheAsset("ui/helpScreen/icons/thrusters.dds"),
    exoEject            = PrecacheAsset("ui/helpScreen/icons/exo_eject.dds"),
    eggStomp            = PrecacheAsset("ui/helpScreen/icons/egg_stomp.dds"),
    jetpack             = PrecacheAsset("ui/helpScreen/icons/jetpack.dds"),
    bite                = PrecacheAsset("ui/helpScreen/icons/bite.dds"),
    parasite            = PrecacheAsset("ui/helpScreen/icons/parasite.dds"),
    leap                = PrecacheAsset("ui/helpScreen/icons/leap.dds"),
    xenocide            = PrecacheAsset("ui/helpScreen/icons/xenocide.dds"),
    healSpray           = PrecacheAsset("ui/helpScreen/icons/heal_spray.dds"),
    spit                = PrecacheAsset("ui/helpScreen/icons/spit.dds"),
    gorgeStructures     = PrecacheAsset("ui/helpScreen/icons/gorge_structures.dds"),
    bileBomb            = PrecacheAsset("ui/helpScreen/icons/bile_bomb.dds"),
    baitBall            = PrecacheAsset("ui/helpScreen/icons/bait_ball.dds"),
    lerkBite            = PrecacheAsset("ui/helpScreen/icons/lerk_bite.dds"),
    spikes              = PrecacheAsset("ui/helpScreen/icons/spikes.dds"),
    umbra               = PrecacheAsset("ui/helpScreen/icons/umbra.dds"),
    spores              = PrecacheAsset("ui/helpScreen/icons/spores.dds"),
    swipe               = PrecacheAsset("ui/helpScreen/icons/swipe.dds"),
    blink               = PrecacheAsset("ui/helpScreen/icons/blink.dds"),
    advancedMetabolize  = PrecacheAsset("ui/helpScreen/icons/advanced_metabolize.dds"),
    metabolize          = PrecacheAsset("ui/helpScreen/icons/metabolize.dds"),
    stab                = PrecacheAsset("ui/helpScreen/icons/stab.dds"),
    gore                = PrecacheAsset("ui/helpScreen/icons/gore.dds"),
    charge              = PrecacheAsset("ui/helpScreen/icons/charge.dds"),
    boneShield          = PrecacheAsset("ui/helpScreen/icons/bone_shield.dds"),
    stomp               = PrecacheAsset("ui/helpScreen/icons/stomp.dds"),
}
function HelpScreen_InitializeContent()
    -- Onos Buffs
     HelpScreen_AddContent({
        name = "Onos_Buff",
        title = "Onos buff",
        description = "Onos have 50% extra HP and unlimited boneshield. Additionally, charge reduces damage by 30%.",
        imagePath = helpScreenImages.charge,
        actions = {},
        classNames = {"Alien", "Marine"},
        theme = "alien",
        useLocale = false,
        })
    -- Jetpack
    HelpScreen_AddContent({
        name = "Jetpack_Fuel",
        title = "Jetpack fuel",
        description = "Jetpacks now have 25% additional fuel.",
        imagePath = helpScreenImages.jetpack,
        actions = {},
        classNames = {"Alien", "Marine"},
        theme = "marine",
        useLocale = true,
        })
end